name: grille
on: push
jobs:
  grille:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dépendances
      run: pip install -r requirements.txt
    - name: génération de grille
      run: |
        set -e
        gunicorn mots_caches:'create_app()' --daemon
        mkdir site
        cd site
        wget http://localhost:8000/
    - name: publication de la grille
      uses: actions/upload-pages-artifact@v1
      with:
        path: site
    - name: publication de la grille étape 2
      id: deployment
      uses: actions/deploy-pages@v2