name: grille
on:
  push:
    branche: [ main ]
  pull_request:
    branche: [ main ]
  schedul: ## Tout les mois le 4.
    - cron: '0 0 4 * *'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  grille:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dépendances
      run: pip install -r requirements.txt
    - name: génération de grille
      run: |
        set -ex
        gunicorn mots_caches:'create_app()' --daemon
        mkdir site
        cd site
        while ! wget http://localhost:8000/; do :; done
    - name: publication de la grille
      uses: actions/upload-pages-artifact@v1
      with:
        path: site
    - name: publication de la grille étape 2
      id: deployment
      uses: actions/deploy-pages@v2