name: grille
on: push
jobs:
  grille:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dépendances
      run: pip install -r requirements.txt
    - name: génération de grille
      run: |
        set -e
        gunicorn mots_caches:'create_app()' --daemon
        wget http://localhost:8000/